# create your drupal and postgres config here, based off the last assignment

services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    image: drupal:8
    ports:
      - 8080:80
    volumes:
      - /var/www/html/module
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
    restart: always
  
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - /var/lib/postgresql/data
    restart: always
